# Generated by Django 3.2.16 on 2023-01-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='название локации')),
                ('description_short', models.TextField(verbose_name='Короткое описание')),
                ('description_long', models.TextField(verbose_name='Полное описание')),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Долгота')),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22, verbose_name='Широта')),
            ],
        ),
    ]
