# Generated by Django 3.2.16 on 2023-01-14 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Изображение')),
                ('number', models.IntegerField(default=1, verbose_name='Номер изображения')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.place', verbose_name='Локация')),
            ],
        ),
    ]
