# Generated by Django 3.2.16 on 2023-01-21 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20230115_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='place',
        ),
    ]
